apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: es-logger
  name: es-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      service: es-logger
  strategy: {}
  template:
    metadata:
      labels:
        service: es-logger
    spec:
      containers:
        - image: guestros/elasticsearch-logger-endpoint:latest
          name: es-logger
          ports:
            - containerPort: 5000
          resources: {}
          env:
            - name: AUTH_PW
              value: testitest
            - name: ES_HOST
              value: elasticsearch
            - name: ES_PW
              value: changeme
            - name: ES_USER
              value: elastic
          
      restartPolicy: Always
status: {}
